version: '3'

services:
  backend:
    build: ./backend
    command: python -m flask run --host=0.0.0.0
    volumes:
      - ./backend:/docker-backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  react:
    build: ./frontend
    command: asdfadf
    volumes:
      - ./frontend:/docker-frontend
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend